import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { backendClient } from "@/services/backendClient";
import Layout from "@/components/Layout";
import ImageCard from "@/components/molecules/ImageCard";
import ArtImage from "@/components/molecules/ArtImage";

export default function ArtPage() {
  const router = useRouter();
  const { id } = router.query;

  const [art, setArt] = useState();

  useEffect(() => {
    async function getArt() {
      const response = await backendClient.get(`art/${id}`);
      setArt(response.result);
    }
    getArt();
  }, []);

  if (!art) {
    return <>Loading...</>;
  }

  const { headline, votes, date, imageUrl, seed, selected } = art;

  return (
    <Layout
      title={`Art ${id}`}
      description="This art was generated by an AI with the input of an wordly event of its date. Now embrace its uniquenes and become its owner!"
    >
      <main style={{ padding: 16, textAlign: "-webkit-center" }}>
        <ImageCard key={id}>
          <ImageCard.Heading>{headline}</ImageCard.Heading>
          <ImageCard.Image>
            <ArtImage imageUrl={imageUrl} alt={headline} size="available" />
          </ImageCard.Image>
          <ImageCard.PropsWrapper>
            <ImageCard.ButtonProp>Mint NFT</ImageCard.ButtonProp>
            <ImageCard.SelectProp
              type="art"
              id={id}
              selected={selected}
              closed={true}
            />
            <ImageCard.VoteProp
              type="art"
              id={id}
              votes={votes}
              closed={true}
            />
            <ImageCard.Prop>{seed}</ImageCard.Prop>
            <ImageCard.Prop>{date}</ImageCard.Prop>
          </ImageCard.PropsWrapper>
        </ImageCard>
      </main>
    </Layout>
  );
}
